# -*- coding: utf-8 -*-
"""ML-based-PCF-SPR-sensor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORDz2wX1d_i9TkRlqO56vJiedalUPX2M
"""

from google.colab import drive
drive.mount('/content/MyDrive/')

#!pip install xgboost
#!pip install lightgbm
!pip install catboost

import numpy as np
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense , Dropout
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras import initializers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
import seaborn as sns
import time

!pip install shap scikit-learn matplotlib numpy
import shap

"""# Loading Data"""

import pandas as pd
df = pd.read_csv('/content/MyDrive/MyDrive/Projects/Fahim /Final_Dataset - v2.csv')
df.shape

df.isnull().sum()

df['rg(nm)'].value_counts()

# Select only the required columns
selected_df = df[["Wavelength", "Loss"]]
"""
# Save to CSV
file_name = "wavelength_confinement_loss.csv"
selected_df.to_csv(file_name, index=False)

from google.colab import files
files.download(file_name)
"""

X = df.drop(['Loss', 'EMI', 'SA(1/RIU)'], axis=1)
#X = df.drop(['Loss', 'SA(1/RIU)'], axis=1)
y = df[['Loss']]
X.shape, y.shape

X.isnull().sum()

X['N^2'] = X['N'] * X['N']
X['N^3'] = X['N'] * X['N'] * X['N']
X['N^4'] = X['N'] * X['N'] * X['N'] * X['N']

X['Wavelength^2'] = X['Wavelength'] * X['Wavelength']
X['Wavelength^3'] = X['Wavelength'] * X['Wavelength'] * X['Wavelength']
X['Wavelength^4'] = X['Wavelength'] * X['Wavelength'] * X['Wavelength'] * X['Wavelength']

X['Imag^2'] = X['Imag'] * X['Imag']
X['Imag^3'] = X['Imag'] * X['Imag'] * X['Imag']
X['Imag^4'] = X['Imag'] * X['Imag'] * X['Imag'] * X['Imag']

X.shape

scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

"""# Train Test Split"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)
X_train.shape, X_test.shape

"""# For Loss

# Linear Regression
"""

model = LinearRegression()

model.fit(X_train, y_train)

#X_test = X_test.sample(n=1, random_state=None)
start_time = time.time()
y_pred_test = model.predict(X_test)
end_time = time.time()

execution_time_ms = (end_time - start_time) * 1000
print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = model.predict(X_train)

print(f"r2score = {r2_score(y_test, y_pred_test)}")
print(f"MAE = {mean_absolute_error(y_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_test, y_pred_test))}")

print(f"r2score = {r2_score(y_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")
"""

lr_model = LinearRegression()
cv_scores_lr = cross_val_score(lr_model, X, y, cv=5, scoring='r2')

# Cross-validated predictions
y_pred = cross_val_predict(lr_model, X, y, cv=7)

# Evaluation metrics
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

print(f"MAE: {mae:.4f}")
print(f"MSE: {mse:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"Linear Regression R² Score: {np.mean(cv_scores_lr):.4f}")

"""SHAP"""

feature_names = X_test.columns
explainer = shap.Explainer(model, X_train) # Pass the fitted model object directly
shap_values = explainer(X_test)

# Convert to DataFrame
shap_df = pd.DataFrame(
    shap_values.values,
    columns=X_test.columns
)

file_path = "shap_values.xlsx"
shap_df.to_excel(file_path, index=False)

shap_values.shape

shap.summary_plot(shap_values.values, X_test, feature_names=X_test.columns)

shap.summary_plot(
    shap_values.values,
    X_test,
    feature_names=X_test.columns,
    plot_type="bar"
)

shap.waterfall_plot(shap_values[0])

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(lr_model, X_test, y_test, cv=7)
y_pred_train = cross_val_predict(lr_model, X_train, y_train, cv=7)

# Define boundaries
X_min = min(y_test.values.min(), y_pred_test.min())
X_max = max(y_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
rf_csv = pd.DataFrame()
#rf_csv['x1'] = list(y_train.values)
#rf_csv['y1'] = list(y_pred_train)
#rf_csv['x2'] = list(y_test.values)
#rf_csv['y2'] = list(y_pred_test)
rf_csv['x3'] = list(x3)
rf_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
rf_csv.to_csv('rf_loss_csv_2.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('rf_loss_csv_2.csv')

"""**2. Ridge Regression (L2)**"""

ridge_model = Ridge(alpha=1.0)
cv_scores_ridge = cross_val_score(ridge_model, X, y, cv=5, scoring='r2')
print(f"Ridge Regression R² Score: {np.mean(cv_scores_ridge):.4f}")

"""**3. Lasso Regression (L1)**"""

lasso_model = Lasso(alpha=0.1)
cv_scores_lasso = cross_val_score(lasso_model, X, y, cv=10, scoring='r2')
print(f"Lasso Regression R² Score: {np.mean(cv_scores_lasso):.4f}")

"""**4. ElasticNet Regression (L1 + L2)**"""

elastic_model = ElasticNet(alpha=0.1, l1_ratio=0.5)
cv_scores_elastic = cross_val_score(elastic_model, X, y, cv=10, scoring='r2')
print(f"ElasticNet Regression R² Score: {np.mean(cv_scores_elastic):.4f}")

"""# Desicion Tree"""

dt_model = DecisionTreeRegressor(random_state=42,
                                 criterion='friedman_mse',
                                 splitter='best',
                                 min_samples_split=2,
                                 min_samples_leaf=1,
                                 max_depth=None)

dt_model.fit(X_train, y_train)
X_test = X_test.sample(n=1, random_state=None)
start = time.time()
y_pred_test = dt_model.predict(X_test)
end = time.time()
execution_time_ms = (end - start) * 1000
print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = dt_model.predict(X_train)
print(f"MAE = {mean_absolute_error(y_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_test, y_pred_test))}")
print(f"r2score = {r2_score(y_test, y_pred_test)}")
"""

print(f"r2score = {r2_score(y_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")

# Define and fit the model
dt_model = DecisionTreeRegressor(random_state=42,
                                 criterion='friedman_mse',
                                 splitter='best',
                                 min_samples_split=2,
                                 min_samples_leaf=1,
                                 max_depth=None)
# Flatten the target array for sklearn compatibility
y_train_flat = y_train.values.ravel()
y_flat = y.values.ravel()

cv_scores_dt = cross_val_score(dt_model, X, y_flat, cv=10, scoring='r2')
y_pred_dt = cross_val_predict(dt_model, X, y_flat, cv=10)


# Calculate Error Metrics
mae = mean_absolute_error(y_flat, y_pred_dt)
mse = mean_squared_error(y_flat, y_pred_dt)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_dt):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(dt_model, X_test, y_test, cv=9)
y_pred_train = cross_val_predict(dt_model, X_train, y_train, cv=9)

# Define boundaries
X_min = min(y_test.values.min(), y_pred_test.min())
X_max = max(y_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
dt_csv['x1'] = list(y_train.values)
dt_csv['y1'] = list(y_pred_train)
#dt_csv['x2'] = list(y_test.values)
#dt_csv['y2'] = list(y_pred_test)
#dt_csv['x3'] = list(x3)
#dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('dt_loss_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('dt_loss_3.csv')

"""# Random Forest"""

rf_model = RandomForestRegressor(n_estimators=175,
                                 random_state=42,
                                 max_depth=15,
                                 max_features='sqrt',
                                 min_samples_leaf=1,
                                 min_samples_split=2)
rf_model.fit(X_train, y_train)
#X_test = X_test.sample(n=1, random_state=None)
#start = time.time()
y_pred_rfr = rf_model.predict(X)
#end = time.time()
#execution_time_ms = (end - start) * 1000
#print(f"Execution time: {execution_time_ms:.3f} ms")

y_pred_train = rf_model.predict(X_train)

print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")
print(f"r2score = {r2_score(y_train, y_pred_train)}")

"""
# Convert predictions to DataFrame
y_pred_df = pd.DataFrame(y_pred_rfr, columns=["RFR (Y2)"])

# Save to CSV
file_name = "model_predictions.csv"
y_pred_df.to_csv(file_name, index=False)

files.download(file_name)
"""

print(f"r2score = {r2_score(y_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")

# Define and fit the model
rf_model = RandomForestRegressor(n_estimators=175,
                                 random_state=42,
                                 max_depth=15,
                                 max_features='sqrt',
                                 min_samples_leaf=1,
                                 min_samples_split=2)
# Flatten the target array for sklearn compatibility
y_train_flat = y_train.values.ravel()
y_flat = y.values.ravel()

cv_scores_rf = cross_val_score(rf_model, X, y_flat, cv=5, scoring='r2')
y_pred = cross_val_predict(rf_model, X, y_flat, cv=5)


# Calculate Error Metrics
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_rf):.4f}")

# Outside Dataset Test
cv_scores_rf = cross_val_score(rf_model, X, y, cv=5, scoring='r2')
y_pred = cross_val_predict(rf_model, X, y, cv=5)

mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_rf):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(rf_model, X_test, y_test, cv=5)
y_pred_train = cross_val_predict(rf_model, X_train, y_train, cv=5)

# Define boundaries
X_min = min(y_test.values.min(), y_pred_test.min())
X_max = max(y_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
#dt_csv['x1'] = list(y_train.values)
#dt_csv['y1'] = list(y_pred_train)
dt_csv['x2'] = list(y_test.values)
dt_csv['y2'] = list(y_pred_test)
#dt_csv['x3'] = list(x3)
#dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('rf_loss_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('rf_loss_3.csv')

# Define parameter grid
param_grid = {
    'n_estimators': [25,50,100,125,150,175,200],
    'max_depth': [None, 5,10,15,20,25,30],
    'min_samples_split': [2,3,4,5],
    'min_samples_leaf': [1,2,3,4,5],
    'max_features': ['sqrt', 'log2']
}

# Create GridSearchCV object
grid_search = GridSearchCV(estimator=rf_model,
                           param_grid=param_grid,
                           cv=10,
                           scoring='r2',
                           n_jobs=-1,
                           verbose=2)

# Fit the model
grid_search.fit(X, y.values.ravel())

# Print best parameters and R2 score
print("Best Parameters:", grid_search.best_params_)
print("Best R2 Score:", grid_search.best_score_)

"""# GBoost"""

gb_model = GradientBoostingRegressor(random_state=42)

gb_model.fit(X_train, y_train)
#X_test = X_test.sample(n=1, random_state=None)
#start = time.time()
#y_pred_gb = gb_model.predict(X_train)
#end = time.time()
#execution_time_ms = (end - start) * 1000
#print(f"Execution time: {execution_time_ms:.3f} ms")

y_pred_train = gb_model.predict(X_train)
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")
print(f"r2score = {r2_score(y_train, y_pred_train)}")

"""
# Convert predictions to DataFrame
y_pred_df = pd.DataFrame(y_pred_gb, columns=["GB (Y3)"])

# Save to CSV
file_name = "model_predictions.csv"
y_pred_df.to_csv(file_name, index=False)

files.download(file_name)
"""

print(f"r2score = {r2_score(y_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")

explainer_gb = shap.TreeExplainer(gb_model)
shap_values_gb = explainer_gb.shap_values(X_test)

shap.summary_plot(
    shap_values_gb,
    X_test,
    feature_names=X_test.columns,
    show=False      # ⭐ important
)

plt.savefig("shap_summary_loss.png", dpi=300, bbox_inches="tight")
plt.close()

shap.summary_plot(
    shap_values_gb,
    X_test,
    feature_names=X_test.columns,
    plot_type="bar"
)

shap.waterfall_plot(
    shap.Explanation(
        values=shap_values_gb[0],
        base_values=explainer_gb.expected_value,
        data=X_test.iloc[0],
        feature_names=X_test.columns
    ),
    show=False      # ⭐ important
)

plt.savefig("shap_waterfall_loss.png", dpi=300, bbox_inches="tight")
plt.close()

gb_model = GradientBoostingRegressor(random_state=42)

y_flat = y.values.ravel()
cv_scores_gb = cross_val_score(gb_model, X, y_flat, cv=5, scoring='r2')

y_pred = cross_val_predict(gb_model, X, y_flat, cv=5)

# Calculate Error Metrics
mae = mean_absolute_error(y_flat, y_pred)
mse = mean_squared_error(y_flat, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_gb):.4f}")

# Outside Dataset Test
cv_scores_rf = cross_val_score(gb_model, X, y, cv=5, scoring='r2')
y_pred = cross_val_predict(gb_model, X, y, cv=5)

mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_rf):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(gb_model, X_test, y_test, cv=5)
y_pred_train = cross_val_predict(gb_model, X_train, y_train, cv=5)

# Define boundaries
X_min = min(y_test.values.min(), y_pred_test.min())
X_max = max(y_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
#dt_csv['x1'] = list(y_train.values)
#dt_csv['y1'] = list(y_pred_train)
#dt_csv['x2'] = list(y_test.values)
#dt_csv['y2'] = list(y_pred_test)
dt_csv['x3'] = list(x3)
dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('gb_loss_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('gb_loss_3.csv')

# Define the parameter grid
param_grid = {
    'n_estimators': [25,50,75,100,125,150,175,200],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 3],
    'subsample': [0.8, 1.0],
    'max_features': ['sqrt', 'log2']
}

# Create the GridSearchCV object
grid_search = GridSearchCV(
    estimator=gb_model,
    param_grid=param_grid,
    cv=10,
    scoring='r2',
    n_jobs=-1,
    verbose=2
)

# Fit on training data
grid_search.fit(X, y)

# Best parameters and R² score
print("Best Parameters:", grid_search.best_params_)
print("Best R² Score:", grid_search.best_score_)

"""# XGBoost"""

xgb_model = XGBRegressor(n_estimators=200,
                         learning_rate=0.1,
                         colsample_bytree=1.0,
                         gamma=0,
                         max_depth=5,
                         min_child_weight=2,
                         reg_alpha=0.1,
                         reg_lambda=2.0,
                         subsample=1.0,
                         random_state=42)
xgb_model.fit(X_train, y_train)
X_test = X_test.sample(n=1, random_state=None)
start = time.time()
y_pred_test = xgb_model.predict(X_test)
end = time.time()
execution_time_ms = (end - start) * 1000
print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = xgb_model.predict(X_train)
print(f"MAE = {mean_absolute_error(y_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_test, y_pred_test))}")
print(f"r2score = {r2_score(y_test, y_pred_test)}")
"""

print(f"r2score = {r2_score(y_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")

xgb_model = XGBRegressor(n_estimators=200,
                         learning_rate=0.1,
                         colsample_bytree=1.0,
                         gamma=0,
                         max_depth=5,
                         min_child_weight=2,
                         reg_alpha=0.1,
                         reg_lambda=2.0,
                         subsample=1.0,
                         random_state=42)
cv_scores_xgb = cross_val_score(xgb_model, X, y, cv=10, scoring='r2')
y_pred = cross_val_predict(xgb_model, X, y, cv=10)

# Calculate Error Metrics
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_xgb):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(xgb_model, X_test, y_test, cv=10)
y_pred_train = cross_val_predict(xgb_model, X_train, y_train, cv=10)

# Define boundaries
X_min = min(y_test.values.min(), y_pred_test.min())
X_max = max(y_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
#dt_csv['x1'] = list(y_train.values)
#dt_csv['y1'] = list(y_pred_train)
#dt_csv['x2'] = list(y_test.values)
#dt_csv['y2'] = list(y_pred_test)
dt_csv['x3'] = list(x3)
dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('xgb_loss_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('xgb_loss_3.csv')

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [25,50,75,100,125,150,175,200],
    'learning_rate': [0.01,0.05,0.1],
    'max_depth': [2,3,4,5],
    'min_child_weight': [1,2, 3],
    'gamma': [0, 0.1],
    'subsample': [0.8,0.9,1.0],
    'colsample_bytree': [0.8, 1.0],
    'reg_alpha': [0, 0.1],
    'reg_lambda': [1.0, 2.0],
}

# Setup GridSearchCV
grid_search = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid,
    scoring='r2',
    cv=10,
    verbose=2,
    n_jobs=-1
)

# Fit on your data
grid_search.fit(X, y)

# Best model and score
print("Best Parameters:", grid_search.best_params_)
print("Best R² Score:", grid_search.best_score_)

"""# Light GBM"""

lgbm_model = LGBMRegressor(colsample_bytree=0.8,
                           learning_rate=0.2,
                           max_depth=10,
                           num_leaves=70,
                           reg_alpha=0.1,
                           reg_lambda=0.1,
                           n_estimators=25,
                           subsample=0.8,
                           random_state=42)

lgbm_model.fit(X_train, y_train)
X_test = X_test.sample(n=1, random_state=None)
start = time.time()
y_pred_test = lgbm_model.predict(X_test)
end = time.time()
execution_time_ms = (end - start) * 1000
print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = lgbm_model.predict(X_train)
print(f"MAE = {mean_absolute_error(y_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_test, y_pred_test))}")
print(f"r2score = {r2_score(y_test, y_pred_test)}")
"""

print(f"r2score = {r2_score(y_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")

lgbm_model = LGBMRegressor(colsample_bytree=0.8,
                           learning_rate=0.2,
                           max_depth=10,
                           num_leaves=70,
                           reg_alpha=0.1,
                           reg_lambda=0.1,
                           n_estimators=25,
                           subsample=0.8,
                           random_state=42)
cv_scores_lgbm = cross_val_score(lgbm_model, X, y, cv=10, scoring='r2')
y_pred = cross_val_predict(lgbm_model, X, y, cv=10)

# Calculate Error Metrics
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_lgbm):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(lgbm_model, X_test, y_test, cv=10)
y_pred_train = cross_val_predict(lgbm_model, X_train, y_train, cv=10)

# Define boundaries
X_min = min(y_test.values.min(), y_pred_test.min())
X_max = max(y_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
dt_csv['x1'] = list(y_train.values)
dt_csv['y1'] = list(y_pred_train)
#dt_csv['x2'] = list(y_test.values)
#dt_csv['y2'] = list(y_pred_test)
#dt_csv['x3'] = list(x3)
#dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('lgbm_loss_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('lgbm_loss_3.csv')

# Define the parameter grid
param_grid = {
    'num_leaves': [31, 50, 70],
    'max_depth': [-1, 10, 20],
    'learning_rate': [0.01,0.05,0.1,0.2],
    'n_estimators': [25,50,75,100,125,150,175,200],
    'subsample': [0.8, 0.9,1.0],
    'colsample_bytree': [0.8, 1.0],
    'reg_alpha': [0.0, 0.1],
    'reg_lambda': [0.0, 0.1]
}

# Setup GridSearchCV
grid_search = GridSearchCV(estimator=lgbm_model,
                           param_grid=param_grid,
                           scoring='r2',          # r2 score
                           cv=10,                 # 10-fold CV
                           n_jobs=-1,             # Use all cores
                           verbose=0)

# Fit the model
grid_search.fit(X, y)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best R2 Score:", grid_search.best_score_)

"""# CatBoost"""

cat_model = CatBoostRegressor(verbose=0,
                              bagging_temperature=0.2,
                              depth=4,
                              iterations=500,
                              l2_leaf_reg=1,
                              learning_rate=0.1,
                              random_state=42)

cat_model.fit(X_train, y_train)
#X_test = X_test.sample(n=1, random_state=None)
#start = time.time()
#y_pred_catb = cat_model.predict(X)
#end = time.time()
#execution_time_ms = (end - start) * 1000
#print(f"Execution time: {execution_time_ms:.3f} ms")

y_pred_train = cat_model.predict(X_train)
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")
print(f"r2score = {r2_score(y_train, y_pred_train)}")
"""

# Convert predictions to DataFrame
y_pred_df = pd.DataFrame(y_pred_catb, columns=["CATB (Y4)"])

# Save to CSV
file_name = "model_predictions.csv"
y_pred_df.to_csv(file_name, index=False)

files.download(file_name)
"""

print(f"r2score = {r2_score(y_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_train, y_pred_train))}")

cat_model = CatBoostRegressor(verbose=0,
                              bagging_temperature=0.2,
                              depth=4,
                              iterations=500,
                              l2_leaf_reg=1,
                              learning_rate=0.1,
                              random_state=42)
cv_scores_cat = cross_val_score(cat_model, X, y, cv=5, scoring='r2')
y_pred = cross_val_predict(cat_model, X, y, cv=5)

# Calculate Error Metrics
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_cat):.4f}")

# Outside Dataset Test
cv_scores_rf = cross_val_score(cat_model, X, y, cv=5, scoring='r2')
y_pred = cross_val_predict(cat_model, X, y, cv=5)

mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_rf):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(cat_model, X_test, y_test, cv=5)
y_pred_train = cross_val_predict(cat_model, X_train, y_train, cv=5)

# Define boundaries
X_min = min(y_test.values.min(), y_pred_test.min())
X_max = max(y_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
dt_csv['x1'] = list(y_train.values)
dt_csv['y1'] = list(y_pred_train)
#dt_csv['x2'] = list(y_test.values)
#dt_csv['y2'] = list(y_pred_test)
#dt_csv['x3'] = list(x3)
#dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('cat_loss_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('cat_loss_3.csv')

# Define the parameter grid
param_grid = {
    'iterations': [200, 500],
    'learning_rate': [0.01, 0.05, 0.1],
    'depth': [4, 6, 8],
    'l2_leaf_reg': [1, 3, 5],
    'bagging_temperature': [0.2, 0.5, 1.0]
}

# Define the GridSearchCV
grid_search = GridSearchCV(
    estimator=cat_model,
    param_grid=param_grid,
    scoring='r2',
    cv=10,
    n_jobs=-1,
    verbose=1
)

# Fit the grid search to your data
grid_search.fit(X, y)

# Best model
print("Best parameters found: ", grid_search.best_params_)
print("Best R2 score: ", grid_search.best_score_)

"""# SVR"""

svr_model = SVR(kernel='rbf', C=1.0, epsilon=0.1)

svr_model.fit(X_train, y_train)
y_pred_test = svr_model.predict(X_test)
y_pred_train = svr_model.predict(X_train)
print(f"MAE = {mean_absolute_error(y_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_test, y_pred_test))}")
print(f"r2score = {r2_score(y_test, y_pred_test)}")

svr_model = SVR(kernel='rbf', C=1.0, epsilon=0.1)
cv_scores_svr = cross_val_score(svr_model, X, y, cv=10, scoring='r2')
y_pred = cross_val_predict(svr_model, X, y, cv=10)

# Calculate Error Metrics
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_svr):.4f}")

param_grid = {
    'kernel': ['rbf', 'linear'],
    'C': [0.1, 1, 10, 100],
    'epsilon': [0.01, 0.1, 0.5],
    'gamma': ['scale', 'auto']
}

# GridSearchCV with 10-fold CV and R² as scoring metric
grid_search = GridSearchCV(
    estimator=svr_model,
    param_grid=param_grid,
    scoring='r2',        # R-squared scoring
    cv=10,
    n_jobs=-1,           # Use all cores
    verbose=0
)

# Fit to the data
grid_search.fit(X, y)
# Best parameters and best R2 score
print("Best Parameters:", grid_search.best_params_)
print("Best R² Score:", grid_search.best_score_)

"""# KNN"""

knn_model = KNeighborsRegressor(n_neighbors=10)

knn_model.fit(X_train, y_train)
y_pred_test = knn_model.predict(X_test)
y_pred_train = knn_model.predict(X_train)
print(f"MAE = {mean_absolute_error(y_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_test, y_pred_test))}")
print(f"r2score = {r2_score(y_test, y_pred_test)}")

knn_model = KNeighborsRegressor(n_neighbors=10)
cv_scores_knn = cross_val_score(knn_model, X, y, cv=10, scoring='r2')
y_pred = cross_val_predict(knn_model, X, y, cv=10)

# Calculate Error Metrics
mae = mean_absolute_error(y, y_pred)
mse = mean_squared_error(y, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_knn):.4f}")

# Define hyperparameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree'],
    'leaf_size': [20, 30, 40],
    'p': [1, 2]
}

# Set up GridSearchCV
grid_search = GridSearchCV(
    estimator=knn_model,
    param_grid=param_grid,
    cv=10,
    scoring='r2',
    n_jobs=-1,
    verbose=0
)

# Fit the grid search (replace X_train and y_train with your data)
grid_search.fit(X, y)

# Best parameters and R² score
print("Best Parameters:", grid_search.best_params_)
print("Best R² Score:", grid_search.best_score_)

"""# For sensitivity"""

df_sen = pd.read_csv('/content/MyDrive/MyDrive/Projects/Fahim /Dataset 2.csv')
df_sen.shape

df_sen.isnull().sum()

df_sen = df_sen.dropna(axis = 0)
df_sen.isnull().sum()

df_sen['rg(nm)'].value_counts()

# Select only the required columns
selected_df = df_sen[["Wavelength", "SA(1/RIU)"]]

# Save to CSV
file_name = "wavelength_confinement_loss.csv"
selected_df.to_csv(file_name, index=False)

from google.colab import files
files.download(file_name)

X_sen = df_sen.drop(['Loss', 'EMI', 'SA(1/RIU)'], axis=1)
#X_sen = df_sen.drop(['Loss', 'SA(1/RIU)'], axis=1)
y_sen = df_sen[['SA(1/RIU)']]
X_sen.shape, y_sen.shape

X_sen['N^2'] = X_sen['N'] * X_sen['N']
X_sen['N^3'] = X_sen['N'] * X_sen['N'] * X_sen['N']
X_sen['N^4'] = X_sen['N'] * X_sen['N'] * X_sen['N'] * X_sen['N']

X_sen['Wavelength^2'] = X_sen['Wavelength'] * X_sen['Wavelength']
X_sen['Wavelength^3'] = X_sen['Wavelength'] * X_sen['Wavelength'] * X_sen['Wavelength']
X_sen['Wavelength^4'] = X_sen['Wavelength'] * X_sen['Wavelength'] * X_sen['Wavelength'] * X_sen['Wavelength']

X_sen['Imag^2'] = X_sen['Imag'] * X_sen['Imag']
X_sen['Imag^3'] = X_sen['Imag'] * X_sen['Imag'] * X_sen['Imag']
X_sen['Imag^4'] = X_sen['Imag'] * X_sen['Imag'] * X_sen['Imag'] * X_sen['Imag']

X_sen.shape

"""# Train Test Split"""

X_sen_train, X_sen_test, y_sen_train, y_sen_test = train_test_split(X_sen, y_sen, test_size=0.2, random_state=42, shuffle=True)
X_sen_train.shape, X_sen_test.shape

"""# Heatmap

"""

heat = df_sen.drop(['EMI'], axis=1)
correlation_matrix = heat.corr()

plt.figure(figsize=(10, 8)) # Adjust figure size for better readability

sns.heatmap(
    correlation_matrix,
    annot=True,      # Show the correlation values on the heatmap
    cmap='coolwarm', # Colormap: 'coolwarm' for diverging colors (good for correlation)
                     # Other good options: 'viridis', 'plasma', 'YlGnBu', 'RdBu_r'
    fmt=".2f",       # Format annotations to two decimal places
    linewidths=.5    # Add lines between cells for better separation
)

plt.title('Correlation Heatmap of Features', fontsize=16)
plt.show()

output_filename = 'correlation_matrix.csv'
correlation_matrix.to_csv(output_filename, index=True)

from google.colab import files
files.download(output_filename)

"""# Linear regression"""

model = LinearRegression()
model.fit(X_sen_train, y_sen_train)
y_pred_test = model.predict(X_sen_test)
y_pred_train = model.predict(X_sen_train)
print(f"r2score = {r2_score(y_sen_test, y_pred_test)}")
print(f"MAE = {mean_absolute_error(y_sen_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_sen_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_test, y_pred_test))}")

print(f"r2score = {r2_score(y_sen_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_sen_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_sen_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_train, y_pred_train))}")

lr_model = LinearRegression()
cv_scores_lr = cross_val_score(lr_model, X_sen, y_sen, cv=8, scoring='r2')

# Cross-validated predictions
y_pred = cross_val_predict(lr_model, X_sen, y_sen, cv=8)

# Evaluation metrics
mae = mean_absolute_error(y_sen, y_pred)
mse = mean_squared_error(y_sen, y_pred)
rmse = np.sqrt(mse)

print(f"MAE: {mae:.4f}")
print(f"MSE: {mse:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"Linear Regression R² Score: {np.mean(cv_scores_lr):.4f}")

"""**Ridge Regression**"""

ridge_model = Ridge(alpha=1.0)
cv_scores_ridge = cross_val_score(ridge_model, X_sen, y_sen, cv=10, scoring='r2')
print(f"Ridge Regression R² Score: {np.mean(cv_scores_ridge):.4f}")

"""**Lasso Regression**"""

lasso_model = Lasso(alpha=0.1)
cv_scores_lasso = cross_val_score(lasso_model, X_sen, y_sen, cv=10, scoring='r2')
print(f"Lasso Regression R² Score: {np.mean(cv_scores_lasso):.4f}")

"""**ElasticNet Regression**"""

elastic_model = ElasticNet(alpha=0.1, l1_ratio=0.5)
cv_scores_elastic = cross_val_score(elastic_model, X_sen, y_sen, cv=10, scoring='r2')
print(f"ElasticNet Regression R² Score: {np.mean(cv_scores_elastic):.4f}")

"""# Decision Tree"""

dt_model_sen = DecisionTreeRegressor(random_state=42,
                                 criterion='squared_error',
                                 splitter='random',
                                 min_samples_split=2,
                                 min_samples_leaf=1,
                                 max_depth=None,
                                 max_features=None,
                                 max_leaf_nodes=None)

dt_model_sen.fit(X_sen_train, y_sen_train)

X_sen_test = X_sen_test.sample(n=1, random_state=None)
start = time.time()
y_pred_test = dt_model_sen.predict(X_sen_test)
end = time.time()
execution_time_ms = (end - start) * 1000
print(f"Execution time: {execution_time_ms:.3f} ms")

"""
y_pred_train = dt_model_sen.predict(X_sen_train)
print(f"MAE = {mean_absolute_error(y_sen_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_sen_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_test, y_pred_test))}")
print(f"r2score = {r2_score(y_sen_test, y_pred_test)}")
"""

print(f"r2score = {r2_score(y_sen_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_sen_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_sen_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_train, y_pred_train))}")

# Define and fit the model
dt_model_sen = DecisionTreeRegressor(random_state=42,
                                 criterion='squared_error',
                                 splitter='random',
                                 min_samples_split=2,
                                 min_samples_leaf=1,
                                 max_depth=None,
                                 max_features=None,
                                 max_leaf_nodes=None,
                                 )
# Flatten the target array for sklearn compatibility
y_sen_train_flat = y_sen_train.values.ravel()
y_sen_flat = y_sen.values.ravel()

cv_scores_dt = cross_val_score(dt_model_sen, X_sen, y_sen, cv=2, scoring='r2')
y_pred_dt = cross_val_predict(dt_model_sen, X_sen, y_sen, cv=2)


# Calculate Error Metrics
mae = mean_absolute_error(y_sen_flat, y_pred_dt)
mse = mean_squared_error(y_sen_flat, y_pred_dt)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_dt):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(dt_model_sen, X_sen_test, y_sen_test, cv=9)
y_pred_train = cross_val_predict(dt_model_sen, X_sen_train, y_sen_train, cv=9)

# Define boundaries
X_min = min(y_sen_test.values.min(), y_pred_test.min())
X_max = max(y_sen_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
dt_csv['x1'] = list(y_sen_train.values)
dt_csv['y1'] = list(y_pred_train)
#dt_csv['x2'] = list(y_sen_test.values)
#dt_csv['y2'] = list(y_pred_test)
#dt_csv['x3'] = list(x3)
#dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('dt_loss_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('dt_loss_3.csv')

# Define parameter grid
param_grid = {
    'criterion': ['squared_error', 'friedman_mse'],
    'splitter': ['best', 'random'],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': [None, 'auto', 'sqrt', 'log2'],
    'max_leaf_nodes': [None, 10, 20, 30]
}

# Create GridSearchCV object
grid_search = GridSearchCV(
    estimator=dt_model_sen,
    param_grid=param_grid,
    scoring='r2',           # R² score
    cv=10,                  # 10-fold CV
    n_jobs=-1,              # Use all CPU cores
    verbose=1
)

# Fit the model
grid_search.fit(X_sen, y_sen)

# Print best parameters and score
print("Best parameters:", grid_search.best_params_)
print("Best R2 score:", grid_search.best_score_)

"""# Random Forest"""

# Define and fit the model
rf_model_sen = RandomForestRegressor(n_estimators=25,
                                     max_depth =20,
                                     max_features = 'sqrt',
                                     min_samples_leaf=1,
                                     min_samples_split=3,
                                     random_state=42)

rf_model_sen.fit(X_sen_train, y_sen_train)
#X_sen_test = X_sen_test.sample(n=1, random_state=None)

#start = time.time()
y_pred_rfr = rf_model_sen.predict(X_sen)
#end = time.time()
#execution_time_ms = (end - start) * 1000
#print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = rf_model_sen.predict(X_sen_train)
print(f"MAE = {mean_absolute_error(y_sen_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_sen_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_test, y_pred_test))}")
print(f"r2score = {r2_score(y_sen_test, y_pred_test)}")
"""

# Convert predictions to DataFrame
y_pred_df = pd.DataFrame(y_pred_rfr, columns=["RFR (Y2)"])

# Save to CSV
file_name = "model_predictions.csv"
y_pred_df.to_csv(file_name, index=False)

files.download(file_name)

print(f"r2score = {r2_score(y_sen_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_sen_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_sen_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_train, y_pred_train))}")

# Define and fit the model
rf_model_sen = RandomForestRegressor(n_estimators=25,
                                     max_depth =20,
                                     max_features = 'sqrt',
                                     min_samples_leaf=1,
                                     min_samples_split=3,
                                     random_state=42)
# Flatten the target array for sklearn compatibility
y_train_flat = y_sen_train.values.ravel()
y_sen_flat = y_sen.values.ravel()

cv_scores_rf = cross_val_score(rf_model_sen, X_sen, y_sen_flat, cv=5, scoring='r2')
y_pred = cross_val_predict(rf_model_sen, X_sen, y_sen_flat, cv=5)


# Calculate Error Metrics
mae = mean_absolute_error(y_sen_flat, y_pred)
mse = mean_squared_error(y_sen_flat, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_rf):.4f}")

# Outside Dataset Test
cv_scores_rf = cross_val_score(rf_model_sen, X_sen, y_sen, cv=5, scoring='r2')
y_pred = cross_val_predict(rf_model_sen, X_sen, y_sen, cv=5)

mae = mean_absolute_error(y_sen, y_pred)
mse = mean_squared_error(y_sen, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_rf):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(rf_model_sen, X_sen_test, y_sen_test, cv=5)
y_pred_train = cross_val_predict(rf_model_sen, X_sen_train, y_sen_train, cv=5)

# Define boundaries
X_min = min(y_sen_test.values.min(), y_pred_test.min())
X_max = max(y_sen_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
#dt_csv['x1'] = list(y_sen_train.values)
#dt_csv['y1'] = list(y_pred_train)
dt_csv['x2'] = list(y_sen_test.values)
dt_csv['y2'] = list(y_pred_test)
#dt_csv['x3'] = list(x3)
#dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('rf_sen_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('rf_sen_3.csv')

# Define parameter grid
param_grid = {
    'n_estimators': [25,50,100,125,150,175,200],
    'max_depth': [None, 5,10,15,20,25,30],
    'min_samples_split': [2,3,4,5],
    'min_samples_leaf': [1,2,3,4,5],
    'max_features': ['sqrt', 'log2']
}

# Create GridSearchCV object
grid_search = GridSearchCV(estimator=rf_model_sen,
                           param_grid=param_grid,
                           cv=10,
                           scoring='r2',
                           n_jobs=-1,
                           verbose=2)

# Fit the model
grid_search.fit(X_sen, y_sen.values.ravel())

# Print best parameters and R2 score
print("Best Parameters:", grid_search.best_params_)
print("Best R2 Score:", grid_search.best_score_)

"""# GBoost"""

gb_model_sen = GradientBoostingRegressor(n_estimators= 100,
                                         learning_rate= 0.1,
                                         max_depth=5,
                                         min_samples_split=2,
                                         min_samples_leaf=3,
                                         max_features= 'sqrt',
                                         subsample=1.0,
                                         random_state=42)

gb_model_sen.fit(X_sen_train, y_sen_train)
#X_sen_test = X_sen_test.sample(n=1, random_state=None)
#start = time.time()
y_pred_gb = gb_model_sen.predict(X_sen)
#end = time.time()
#execution_time_ms = (end - start) * 1000
#print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = gb_model_sen.predict(X_sen_train)
print(f"MAE = {mean_absolute_error(y_sen_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_sen_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_test, y_pred_test))}")
print(f"r2score = {r2_score(y_sen_test, y_pred_test)}")
"""

# Convert predictions to DataFrame
y_pred_df = pd.DataFrame(y_pred_gb, columns=["GB (Y3)"])

# Save to CSV
file_name = "model_predictions.csv"
y_pred_df.to_csv(file_name, index=False)

files.download(file_name)

print(f"r2score = {r2_score(y_sen_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_sen_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_sen_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_train, y_pred_train))}")

gb_model_sen = GradientBoostingRegressor(n_estimators= 100,
                                         learning_rate= 0.1,
                                         max_depth=5,
                                         min_samples_split=2,
                                         min_samples_leaf=3,
                                         max_features= 'sqrt',
                                         subsample=1.0,
                                         random_state=42)

y_flat = y_sen.values.ravel()
cv_scores_gb = cross_val_score(gb_model_sen, X_sen, y_flat, cv=5, scoring='r2')

y_pred = cross_val_predict(gb_model_sen, X_sen, y_flat, cv=5)

# Calculate Error Metrics
mae = mean_absolute_error(y_flat, y_pred)
mse = mean_squared_error(y_flat, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_gb):.4f}")

# Outside Dataset Test
cv_scores_rf = cross_val_score(gb_model_sen, X_sen, y_sen, cv=5, scoring='r2')
y_pred = cross_val_predict(gb_model_sen, X_sen, y_sen, cv=5)

mae = mean_absolute_error(y_sen, y_pred)
mse = mean_squared_error(y_sen, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_rf):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(gb_model_sen, X_sen_test, y_sen_test, cv=5)
y_pred_train = cross_val_predict(gb_model_sen, X_sen_train, y_sen_train, cv=5)

# Define boundaries
X_min = min(y_sen_test.values.min(), y_pred_test.min())
X_max = max(y_sen_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
dt_csv['x1'] = list(y_sen_train.values)
dt_csv['y1'] = list(y_pred_train)
#dt_csv['x2'] = list(y_sen_test.values)
#dt_csv['y2'] = list(y_pred_test)
#dt_csv['x3'] = list(x3)
#dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('gb_sen_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('gb_sen_3.csv')

# Define the parameter grid
param_grid = {
    'n_estimators': [25,50,75,100,125,150,175,200],
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 3],
    'subsample': [0.8, 1.0],
    'max_features': ['sqrt', 'log2']
}

# Create the GridSearchCV object
grid_search = GridSearchCV(
    estimator=gb_model_sen,
    param_grid=param_grid,
    cv=10,
    scoring='r2',
    n_jobs=-1,
    verbose=1
)

# Fit on training data
grid_search.fit(X_sen, y_sen)

# Best parameters and R² score
print("Best Parameters:", grid_search.best_params_)
print("Best R² Score:", grid_search.best_score_)

"""# XGboost"""

xgb_model_sen = XGBRegressor(n_estimators=50,
                             learning_rate=0.1,
                             colsample_bytree=0.8,
                             gamma=0,
                             max_depth=5,
                             min_child_weight=2,
                             reg_alpha=0.1,
                             reg_lambda=1.0,
                             subsample=0.9,
                             random_state=42)

xgb_model_sen.fit(X_sen_train, y_sen_train)
X_sen_test = X_sen_test.sample(n=1, random_state=None)
start = time.time()
y_pred_test = xgb_model_sen.predict(X_sen_test)
end = time.time()
execution_time_ms = (end - start) * 1000
print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = xgb_model_sen.predict(X_sen_train)
print(f"MAE = {mean_absolute_error(y_sen_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_sen_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_test, y_pred_test))}")
print(f"r2score = {r2_score(y_sen_test, y_pred_test)}")
"""

print(f"r2score = {r2_score(y_sen_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_sen_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_sen_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_train, y_pred_train))}")

xgb_model_sen = XGBRegressor(n_estimators=50,
                             learning_rate=0.1,
                             colsample_bytree=0.8,
                             gamma=0,
                             max_depth=5,
                             min_child_weight=2,
                             reg_alpha=0.1,
                             reg_lambda=1.0,
                             subsample=0.9,
                             random_state=42)
cv_scores_xgb = cross_val_score(xgb_model_sen, X_sen, y_sen, cv=2, scoring='r2')
y_pred = cross_val_predict(xgb_model_sen, X_sen, y_sen, cv=2)

# Calculate Error Metrics
mae = mean_absolute_error(y_sen, y_pred)
mse = mean_squared_error(y_sen, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_xgb):.4f}")

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [25,50,75,100,125,150,175,200],
    'learning_rate': [0.01,0.05,0.1],
    'max_depth': [2,3,4,5],
    'min_child_weight': [1,2, 3],
    'gamma': [0, 0.1],
    'subsample': [0.8,0.9,1.0],
    'colsample_bytree': [0.8, 1.0],
    'reg_alpha': [0, 0.1],
    'reg_lambda': [1.0, 2.0],
}

# Setup GridSearchCV
grid_search = GridSearchCV(
    estimator=xgb_model_sen,
    param_grid=param_grid,
    scoring='r2',
    cv=10,
    verbose=1,
    n_jobs=-1
)

# Fit on your data
grid_search.fit(X_sen, y_sen)

# Best model and score
print("Best Parameters:", grid_search.best_params_)
print("Best R² Score:", grid_search.best_score_)

"""# LightGBM"""

lgbm_model_sen = LGBMRegressor(n_estimators=50,
                               colsample_bytree=0.8,
                               learning_rate=0.1,
                               max_depth=-1,
                               num_leaves=70,
                               reg_alpha=0.0,
                               reg_lambda=0.0,
                               subsample=0.8,
                               random_state=42)

lgbm_model_sen.fit(X_sen_train, y_sen_train)
X_sen_test = X_sen_test.sample(n=1, random_state=None)
start = time.time()
y_pred_test = lgbm_model_sen.predict(X_sen_test)
end = time.time()
execution_time_ms = (end - start) * 1000
print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = lgbm_model_sen.predict(X_sen_train)
print(f"MAE = {mean_absolute_error(y_sen_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_sen_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_test, y_pred_test))}")
print(f"r2score = {r2_score(y_sen_test, y_pred_test)}")
"""

print(f"r2score = {r2_score(y_sen_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_sen_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_sen_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_train, y_pred_train))}")

lgbm_model_sen = LGBMRegressor(n_estimators=50,
                               colsample_bytree=0.8,
                               learning_rate=0.1,
                               max_depth=-1,
                               num_leaves=70,
                               reg_alpha=0.0,
                               reg_lambda=0.0,
                               subsample=0.8,
                               random_state=42)

cv_scores_lgbm = cross_val_score(lgbm_model_sen, X_sen, y_sen, cv=2, scoring='r2')
y_pred = cross_val_predict(lgbm_model_sen, X_sen, y_sen, cv=2)

# Calculate Error Metrics
mae = mean_absolute_error(y_sen, y_pred)
mse = mean_squared_error(y_sen, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_lgbm):.4f}")

# Define the parameter grid
param_grid = {
    'num_leaves': [31, 50, 70],
    'max_depth': [-1, 10, 20],
    'learning_rate': [0.01,0.05,0.1],
    'n_estimators': [25,50,75,100],
    'subsample': [0.8, 0.9,1.0],
    'colsample_bytree': [0.8, 1.0],
    'reg_alpha': [0.0, 0.1],
    'reg_lambda': [0.0, 0.1]
}

# Setup GridSearchCV
grid_search = GridSearchCV(estimator=lgbm_model_sen,
                           param_grid=param_grid,
                           scoring='r2',          # r2 score
                           cv=10,                 # 10-fold CV
                           n_jobs=-1,             # Use all cores
                           verbose=1)

# Fit the model
grid_search.fit(X_sen, y_sen)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best R2 Score:", grid_search.best_score_)

"""# CatBoost"""

cat_model_sen = CatBoostRegressor(verbose=0,
                              bagging_temperature=0.2,
                              depth=4,
                              iterations=500,
                              l2_leaf_reg=1,
                              learning_rate=0.1,
                              random_state=42)
cat_model_sen.fit(X_sen_train, y_sen_train)

#start = time.time()
y_pred_catb = cat_model_sen.predict(X_sen)
#end = time.time()
#execution_time_ms = (end - start) * 1000
#print(f"Execution time: {execution_time_ms:.3f} ms")
"""
y_pred_train = cat_model_sen.predict(X_sen_train)
print(f"MAE = {mean_absolute_error(y_sen_test, y_pred_test)}")
print(f"MSE = {mean_squared_error(y_sen_test, y_pred_test)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_test, y_pred_test))}")
print(f"r2score = {r2_score(y_sen_test, y_pred_test)}")
"""

# Convert predictions to DataFrame
y_pred_df = pd.DataFrame(y_pred_catb, columns=["CATB (Y4)"])

# Save to CSV
file_name = "model_predictions.csv"
y_pred_df.to_csv(file_name, index=False)

files.download(file_name)

print(f"r2score = {r2_score(y_sen_train, y_pred_train)}")
print(f"MAE = {mean_absolute_error(y_sen_train, y_pred_train)}")
print(f"MSE = {mean_squared_error(y_sen_train, y_pred_train)}")
print(f"RMSE = {np.sqrt(mean_squared_error(y_sen_train, y_pred_train))}")

cat_model_sen = CatBoostRegressor(verbose=0,
                              bagging_temperature=0.2,
                              depth=8,
                              iterations=500,
                              l2_leaf_reg=5,
                              learning_rate=0.05,
                              random_state=42)
cv_scores_cat = cross_val_score(cat_model_sen, X_sen, y_sen, cv=5, scoring='r2')
y_pred = cross_val_predict(cat_model_sen, X_sen, y_sen, cv=5)

# Calculate Error Metrics
mae = mean_absolute_error(y_sen, y_pred)
mse = mean_squared_error(y_sen, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Gradient Boosting R² Score (10-fold CV): {np.mean(cv_scores_cat):.4f}")

from catboost.core import Pool

shap_values_cat = cat_model_sen.get_feature_importance(
    Pool(X_sen_test, label=y_sen_test),
    type="ShapValues"
)

shap_values_cat_only = shap_values_cat[:, :-1]
base_values_cat = shap_values_cat[:, -1]

shap.summary_plot(
    shap_values_cat_only,
    X_sen_test,
    feature_names=X_sen_test.columns,
    show=False      # ⭐ important
)

plt.savefig("shap_summary_sensitivity.png", dpi=300, bbox_inches="tight")
plt.close()

idx = np.random.randint(0, X_sen_test.shape[0])

shap.waterfall_plot(
    shap.Explanation(
        values=shap_values_cat_only[idx],
        base_values=base_values_cat[idx],
        data=X_sen_test.iloc[idx],
        feature_names=X_sen_test.columns
    ),
    show=False        # ⭐ important
)

plt.savefig(
    "shap_waterfall_sensitivity.png",
    dpi=300,
    bbox_inches="tight"
)
plt.close()

# Outside Dataset Test
cv_scores_rf = cross_val_score(cat_model_sen, X_sen, y_sen, cv=5, scoring='r2')
y_pred = cross_val_predict(cat_model_sen, X_sen, y_sen, cv=5)

mae = mean_absolute_error(y_sen, y_pred)
mse = mean_squared_error(y_sen, y_pred)
rmse = np.sqrt(mse)

# Display results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Random Forest R² Score (10-fold CV): {np.mean(cv_scores_rf):.4f}")

def generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max, sampling_rate=0.1,
                                   plot_line=True, figsize=(8, 6), line_color='black',
                                   line_width=2, alpha=1.0, show_grid=True):

    # Calculate the valid range for y=x line within the given boundaries
    line_start = max(X_min, Y_min)
    line_end = min(X_max, Y_max)

    # Check if the line is visible within the boundaries
    if line_start > line_end:
        print(f"Warning: y=x line does not intersect with the given boundaries!")
        print(f"X range: [{X_min}, {X_max}], Y range: [{Y_min}, {Y_max}]")
        print(f"Line would need coordinates from {line_start} to {line_end}")

        # Return empty arrays if no intersection
        return np.array([]), np.array([])

    # Generate coordinates with the specified sampling rate
    # Use arange to get exact sampling rate, then ensure we include the endpoint
    x3 = np.arange(line_start, line_end + sampling_rate, sampling_rate)

    # Ensure the last point doesn't exceed line_end due to floating point precision
    x3 = x3[x3 <= line_end]

    # For y=x equation, y-coordinates are same as x-coordinates
    y3 = x3.copy()

    # Plot the dashed line if requested
    if plot_line:
        plt.figure(figsize=figsize)

        # Plot the dashed line
        plt.plot(x3, y3, linestyle='--', color=line_color,
                linewidth=line_width, alpha=alpha, label=f'y = x (sampling: {sampling_rate})')

        # Set axis limits
        plt.xlim(X_min, X_max)
        plt.ylim(Y_min, Y_max)

        # Add labels and formatting
        plt.xlabel('X')
        plt.ylabel('Y')
        plt.title(f'y = x')

        if show_grid:
            plt.grid(True, alpha=0.3)

        plt.legend()
        plt.tight_layout()
        plt.show()

    return x3, y3

y_pred_test = cross_val_predict(cat_model_sen, X_sen_test, y_sen_test, cv=5)
y_pred_train = cross_val_predict(cat_model_sen, X_sen_train, y_sen_train, cv=5)

# Define boundaries
X_min = min(y_sen_test.values.min(), y_pred_test.min())
X_max = max(y_sen_test.values.max(), y_pred_test.max())
Y_min = X_min
Y_max = X_max

# Get coordinates and plot
x3, y3 = generate_y_equals_x_coordinates(X_min, X_max, Y_min, Y_max)

# Saving the dataframe
from google.colab import files

# Assuming 'df' is your DataFrame
dt_csv = pd.DataFrame()
dt_csv['x1'] = list(y_sen_train.values)
dt_csv['y1'] = list(y_pred_train)
#dt_csv['x2'] = list(y_sen_test.values)
#dt_csv['y2'] = list(y_pred_test)
#dt_csv['x3'] = list(x3)
#dt_csv['y3'] = list(y3)

# Convert the DataFrame to a CSV file in Colab's temporary storage
dt_csv.to_csv('cat_sen_3.csv', index=False)

# This will trigger a download of the file to your local machine
files.download('cat_sen_3.csv')

# Define the parameter grid
param_grid = {
    'iterations': [200, 500],
    'learning_rate': [0.01, 0.05, 0.1],
    'depth': [4, 6, 8],
    'l2_leaf_reg': [1, 3, 5],
    'bagging_temperature': [0.2, 0.5, 1.0]
}

# Define the GridSearchCV
grid_search = GridSearchCV(
    estimator=cat_model_sen,
    param_grid=param_grid,
    scoring='r2',
    cv=10,
    n_jobs=-1,
    verbose=1
)

# Fit the grid search to your data
grid_search.fit(X_sen, y_sen)

# Best model
print("Best parameters found: ", grid_search.best_params_)
print("Best R2 score: ", grid_search.best_score_)